# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 01:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='例句表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('漢字', models.CharField(max_length=255)),
                ('臺羅', models.CharField(max_length=255)),
                ('華語', models.CharField(max_length=255)),
                ('其他', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='例句音檔表',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('啥人唸的', models.CharField(max_length=255)),
                ('加入時間', models.DateTimeField(auto_now_add=True)),
                ('音檔', models.FileField(upload_to='')),
                ('實際唸的漢字', models.CharField(blank=True, max_length=255)),
                ('實際唸的臺羅', models.CharField(blank=True, max_length=255)),
                ('例句', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='資料', to='收音.例句表')),
            ],
        ),
    ]
